#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby-2.2.1

alias mvim="mvim --remote-tab-silent"

export PATH=$PATH:./node_modules/.bin
export PATH="/opt/homebrew-cask/Caskroom/postgres-app/9.3.1.0-alpha1/Postgres93.app/Contents/MacOS/bin:$PATH"

export JAVA_HOME="$(/usr/libexec/java_home)"

export PATH=~/.cabal/bin:$PATH
export CHROME_BIN=/opt/homebrew-cask/Caskroom/google-chrome/stable-channel/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

export PKG_CONFIG_PATH=/usr/X11/lib/pkgconfig/:$PKG_CONFIG_PATH

export PATH=$PATH:/usr/local/opt/go/libexec/bin

export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export PATH="/Users/pole/anaconda2/bin:$PATH"
